# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='arquivos', verbose_name='Arquivo')),
                ('dt_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('dt_process', models.DateTimeField(editable=False, null=True, verbose_name='Data do processamento')),
            ],
            options={
                'verbose_name': 'Importação',
                'verbose_name_plural': 'Importações',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(db_index=True, editable=False, max_length=10, verbose_name='Nota Fiscal')),
                ('valor', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Valor')),
                ('vencimento', models.DateField(editable=False, verbose_name='Vencimento')),
                ('importacao', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='xlsx.Importacao', verbose_name='Importação')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
